## Notebook 1 for data cleaning and merging

In [1]:
# import
import os
import sys
import csv
import re
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

import gzip

In [2]:

# Dossier contenant les fichiers CSV
folder_path = "Data_spCal"
output_file = "fusion_results.csv.gzip"

# Initialiser une variable pour stocker toutes les lignes extraites
all_data = []
first_file = True

for filename in sorted(os.listdir(folder_path)):
    print(f"Files in process : {filename}")
    if not filename.endswith(".csv"):
        continue

    file_path = os.path.join(folder_path, filename)

    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    try:
        start_idx = next(i for i, line in enumerate(lines) if "# Raw detection data" in line)
        end_idx = next(i for i, line in enumerate(lines) if "# End of export" in line)
    except StopIteration:
        print(f"Missing lines in {filename}, ignored.")
        continue

    block = lines[start_idx + 1:end_idx]  # exclut "# Raw detection data" et "# End of export"

    if first_file:
        if len(block) > 1:
            block = block[:-1]  # Supprimer la ligne juste avant # End of export

        modified_block = []
        for i, line in enumerate(block):
            line = line.strip()
            if i == 0:  # La 3e ligne après "# Raw detection data" est le header
                modified_block.append(line + ",Filename\n")
            else:
                modified_block.append(line + f",\"{filename}\"\n")
        all_data.extend(modified_block)
        first_file = False
    else:
        if len(block) > 3:
            block = block[2:-1]  # Supprimer unités, headers et la dernière ligne
            modified_block = [line.strip() + f",\"{filename}\"\n" for line in block]
            all_data.extend(modified_block)

# Écriture dans le fichier fusionné
with gzip.open(output_file, "wt", encoding="utf-8") as f_out:
    f_out.writelines(all_data)

print(f"Fusion over : {output_file}")

Files in process : .DS_Store
Files in process : 11-42-19 1136 2357_results.csv
Files in process : 11-44-07 1140 2507_results.csv
Files in process : 11-48-19 1140 2508_results.csv
Files in process : 11-49-09 1136 2358_results.csv
Files in process : 11-52-09 1140 2509_results.csv
Files in process : 11-53-04 1136 2359_results.csv
Files in process : 11-56-02 1140 2510_results.csv
Files in process : 11-56-56 1136 2360_results.csv
Files in process : 11-59-41 1140 2511_results.csv
Files in process : 12-00-54 1136 2361_results.csv
Files in process : 12-03-25 1140 2512_results.csv
Files in process : 12-04-49 1136 2362_results.csv
Files in process : 12-07-21 1140 2513_results.csv
Files in process : 12-08-42 1136 2363_results.csv
Files in process : 12-11-17 1140 2514_results.csv
Files in process : 12-12-31 1136 2364_results.csv
Files in process : 12-16-29 1136 2365_results.csv
Files in process : 12-18-49 1140 2516_results.csv
Files in process : 12-20-25 1136 2366_results.csv
Files in process : 12-22-16 1143 2597_results.csv
Files in process : 12-22-41 1140 2517_results.csv
Files in process : 12-24-19 1136 2367_results.csv
Files in process : 12-26-09 1143 2598_results.csv
Files in process : 12-26-37 1140 2518_results.csv
Files in process : 12-28-31 1136 2368_results.csv
Files in process : 12-30-03 1143 2599_results.csv
Files in process : 12-30-25 1140 2519_results.csv
Files in process : 12-32-30 1136 2369_results.csv
Files in process : 12-34-16 1140 2520_results.csv
Files in process : 12-35-05 1143 2600_results.csv
Files in process : 12-36-41 1136 2370_results.csv
Files in process : 12-38-15 1140 2521_results.csv
Files in process : 12-39-08 1143 2601_results.csv
Files in process : 12-40-39 1136 2371_results.csv
Files in process : 12-42-36 1140 2522_results.csv
Files in process : 12-43-21 1143 2602_results.csv
Files in process : 12-44-51 1136 2372_results.csv
Files in process : 12-46-44 1141 2523_results.csv
Files in process : 12-48-13 1143 2603_results.csv
Files in process : 12-48-53 1136 2373_results.csv
Files in process : 12-50-31 1141 2524_results.csv
Files in process : 12-52-02 1143 2604_results.csv
Files in process : 12-52-51 1136 2374_results.csv
Files in process : 12-54-18 1141 2525_results.csv
Files in process : 12-56-47 1136 2375_results.csv
Files in process : 12-57-13 1143 2605_results.csv
Files in process : 12-59-16 1141 2526_results.csv
Files in process : 13-00-43 1136 2376_results.csv
Files in process : 13-03-44 1141 2527_results.csv
Files in process : 13-04-42 1136 2377_results.csv
Files in process : 13-06-11 1143 2607_results.csv
Files in process : 13-08-45 1136 2378_results.csv
Files in process : 13-09-02 1141 2528_results.csv
Files in process : 13-12-48 1136 2379_results.csv
Files in process : 13-13-44 1141 2529_results.csv
Files in process : 13-16-44 1143 2609_results.csv
Files in process : 13-20-34 1143 2606_results.csv
Files in process : 13-24-30 1143 2608_results.csv
Files in process : 13-24-36 1136 2380_results.csv
Files in process : 13-28-35 1141 2530_results.csv
Files in process : 13-28-44 1136 2381_results.csv
Files in process : 13-29-09 1143 2609_results.csv
Files in process : 13-32-55 1136 2382_results.csv
Files in process : 13-33-47 1141 2531_results.csv
Files in process : 13-38-23 1141 2532_results.csv
Files in process : 13-38-37 1136 2383_results.csv
Files in process : 13-42-46 1136 2384_results.csv
Files in process : 13-43-12 1141 2533_results.csv
Files in process : 13-46-49 1136 2385_results.csv
Files in process : 13-47-50 1141 2534_results.csv
Files in process : 13-50-50 1136 2386_results.csv
Files in process : 13-54-30 1141 2535_results.csv
Files in process : 13-54-53 1143 2610_results.csv
Files in process : 13-54-59 1136 2387_results.csv
Files in process : 13-58-47 1143 2611_results.csv
Files in process : 13-58-54 1136 2388_results.csv
Files in process : 13-59-14 1141 2536_results.csv
Files in process : 14-02-51 1136 2389_results.csv
Files in process : 14-03-19 1143 2612_results.csv
Files in process : 14-03-40 1141 2537_results.csv
Files in process : 14-06-52 1136 2390_results.csv
Files in process : 14-08-53 1141 2538_results.csv
Files in process : 14-09-33 1143 2613_results.csv
Files in process : 14-10-57 1136 2391_results.csv
Files in process : 14-13-23 1143 2614_results.csv
Files in process : 14-13-54 1141 2539_results.csv
Files in process : 14-15-46 1136 2392_results.csv
Files in process : 14-17-19 1143 2615_results.csv
Files in process : 14-20-36 1136 2393_results.csv
Files in process : 14-20-58 1141 2540_results.csv
Files in process : 14-21-20 1143 2616_results.csv
Files in process : 14-25-03 1143 2617_results.csv
Files in process : 14-25-38 1137 2394_results.csv
Files in process : 14-26-04 1141 2541_results.csv
Files in process : 14-29-14 1143 2618_results.csv
Files in process : 14-30-28 1137 2395_results.csv
Files in process : 14-30-35 1141 2542_results.csv
Files in process : 14-34-57 1137 2396_results.csv
Files in process : 14-35-08 1141 2543_results.csv
Files in process : 14-40-17 1137 2397_results.csv
Files in process : 14-42-18 1141 2544_results.csv
Files in process : 14-45-13 1137 2398_results.csv
Files in process : 14-47-30 1143 2619_results.csv
Files in process : 14-50-43 1137 2399_results.csv
Files in process : 14-51-18 1141 2546_results.csv
Files in process : 14-52-14 1143 2620_results.csv
Files in process : 14-56-33 1141 2545_results.csv
Files in process : 14-56-34 1143 2621_results.csv
Files in process : 15-01-11 1143 2622_results.csv
Files in process : 15-06-26 1143 2623_results.csv
Files in process : 15-10-31 1143 2624_results.csv
Files in process : 15-14-06 1137 2400_results.csv
Files in process : 15-15-37 1143 2625_results.csv
Files in process : 15-18-42 1137 2401_results.csv
Files in process : 15-19-46 1143 2626_results.csv
Files in process : 15-20-13 1141 2547_results.csv
Files in process : 15-23-49 1137 2402_results.csv
Files in process : 15-24-13 1141 2548_results.csv
Files in process : 15-24-22 1143 2627_results.csv
Files in process : 15-28-09 1141 2549_results.csv
Files in process : 15-28-31 1143 2628_results.csv
Files in process : 15-28-42 1137 2403_results.csv
Files in process : 15-31-53 1141 2550_results.csv
Files in process : 15-33-13 1137 2404_results.csv
Files in process : 15-33-38 1143 2629_results.csv
Files in process : 15-35-30 1141 2551_results.csv
Files in process : 15-37-38 1143 2630_results.csv
Files in process : 15-37-56 1137 2405_results.csv
Files in process : 15-39-18 1141 2552_results.csv
Files in process : 15-43-00 1137 2406_results.csv
Files in process : 15-43-57 1141 2553_results.csv
Files in process : 15-47-33 1137 2407_results.csv
Files in process : 15-48-12 1141 2554_results.csv
Files in process : 15-52-47 1137 2408_results.csv
Files in process : 15-53-01 1141 2555_results.csv
Files in process : 15-57-41 1137 2409_results.csv
Files in process : 15-57-41 1141 2556_results.csv
Files in process : 16-02-27 1141 2557_results.csv
Files in process : 16-05-50 1145 2667_results.csv
Files in process : 16-07-13 1141 2558_results.csv
Files in process : 16-10-10 1145 2668_results.csv
Files in process : 16-11-08 1142 2559_results.csv
Files in process : 16-13-53 1145 2669_results.csv
Files in process : 16-15-38 1142 2560_results.csv
Files in process : 16-18-36 1135 2307_results.csv
Files in process : 16-18-39 1145 2670_results.csv
Files in process : 16-22-38 1145 2671_results.csv
Files in process : 16-22-44 1135 2308_results.csv
Files in process : 16-23-22 1142 2561_results.csv
Files in process : 16-26-27 1145 2672_results.csv
Files in process : 16-26-40 1135 2309_results.csv
Files in process : 16-27-05 1142 2562_results.csv
Files in process : 16-30-22 1145 2673_results.csv
Files in process : 16-30-33 1144 2631_results.csv
Files in process : 16-30-44 1135 2310_results.csv
Files in process : 16-30-55 1142 2563_results.csv
Files in process : 16-34-42 1142 2564_results.csv
Files in process : 16-34-44 1135 2311_results.csv
Files in process : 16-34-54 1144 2632_results.csv
Files in process : 16-37-47 1145 2675_results.csv
Files in process : 16-38-49 1135 2312_results.csv
Files in process : 16-39-11 1142 2565_results.csv
Files in process : 16-39-42 1144 2633_results.csv
Files in process : 16-41-38 1145 2674_results.csv
Files in process : 16-42-58 1135 2313_results.csv
Files in process : 16-43-02 1142 2566_results.csv
Files in process : 16-44-14 1144 2634_results.csv
Files in process : 16-45-29 1145 2676_results.csv
Files in process : 16-47-03 1142 2567_results.csv
Files in process : 16-47-32 1135 2314_results.csv
Files in process : 16-48-32 1139 2451_results.csv
Files in process : 16-48-47 1144 2635_results.csv
Files in process : 16-49-27 1145 2677_results.csv
Files in process : 16-50-37 1142 2568_results.csv
Files in process : 16-51-35 1135 2315_results.csv
Files in process : 16-52-57 1139 2452_results.csv
Files in process : 16-53-16 1145 2678_results.csv
Files in process : 16-53-19 1144 2636_results.csv
Files in process : 16-54-23 1142 2569_results.csv
Files in process : 16-56-15 1135 2316_results.csv
Files in process : 16-57-02 1145 2679_results.csv
Files in process : 16-57-17 1139 2453_results.csv
Files in process : 16-58-13 1142 2570_results.csv
Files in process : 16-58-43 1144 2637_results.csv
Files in process : 16-59-31 1137 2410_results.csv
Files in process : 17-00-08 1135 2317_results.csv
Files in process : 17-00-46 1145 2680_results.csv
Files in process : 17-01-34 1139 2454_results.csv
Files in process : 17-02-44 1142 2571_results.csv
Files in process : 17-02-50 1144 2638_results.csv
Files in process : 17-03-34 1137 2411_results.csv
Files in process : 17-04-47 1135 2318_results.csv
Files in process : 17-06-16 1139 2455_results.csv
Files in process : 17-06-53 1144 2639_results.csv
Files in process : 17-07-05 1142 2572_results.csv
Files in process : 17-08-00 1145 2681_results.csv
Files in process : 17-08-35 1135 2319_results.csv
Files in process : 17-10-40 1139 2456_results.csv
Files in process : 17-10-49 1142 2573_results.csv
Files in process : 17-11-20 1137 2413_results.csv
Files in process : 17-12-21 1145 2682_results.csv
Files in process : 17-12-53 1135 2320_results.csv
Files in process : 17-14-54 1142 2574_results.csv
Files in process : 17-15-16 1137 2414_results.csv
Files in process : 17-16-22 1145 2683_results.csv
Files in process : 17-16-58 1135 2321_results.csv
Files in process : 17-18-04 1139 2457_results.csv
Files in process : 17-18-37 1142 2575_results.csv
Files in process : 17-19-19 1138 2415_results.csv
Files in process : 17-20-49 1145 2684_results.csv
Files in process : 17-21-16 1135 2322_results.csv
Files in process : 17-21-29 1144 2640_results.csv
Files in process : 17-22-10 1142 2576_results.csv
Files in process : 17-22-41 1139 2458_results.csv
Files in process : 17-23-34 1138 2416_results.csv
Files in process : 17-25-27 1135 2323_results.csv
Files in process : 17-25-39 1145 2685_results.csv
Files in process : 17-25-54 1144 2641_results.csv
Files in process : 17-26-04 1142 2577_results.csv
Files in process : 17-27-15 1138 2417_results.csv
Files in process : 17-27-22 1139 2459_results.csv
Files in process : 17-29-34 1135 2324_results.csv
Files in process : 17-29-43 1145 2686_results.csv
Files in process : 17-30-34 1142 2578_results.csv
Files in process : 17-30-47 1144 2642_results.csv
Files in process : 17-31-19 1138 2418_results.csv
Files in process : 17-31-43 1139 2460_results.csv
Files in process : 17-33-43 1135 2325_results.csv
Files in process : 17-34-53 1138 2419_results.csv
Files in process : 17-36-09 1139 2461_results.csv
Files in process : 17-37-48 1135 2326_results.csv
Files in process : 17-38-34 1138 2420_results.csv
Files in process : 17-40-25 1139 2462_results.csv
Files in process : 17-42-13 1138 2421_results.csv
Files in process : 17-44-43 1139 2463_results.csv
Files in process : 17-45-22 1145 2687_results.csv
Files in process : 17-45-39 1144 2643_results.csv
Files in process : 17-46-07 1138 2422_results.csv
Files in process : 17-48-40 1142 2580_results.csv
Files in process : 17-49-09 1139 2464_results.csv
Files in process : 17-49-43 1144 2644_results.csv
Files in process : 17-50-15 1138 2423_results.csv
Files in process : 17-52-49 1142 2581_results.csv
Files in process : 17-53-23 1145 2688_results.csv
Files in process : 17-53-24 1139 2465_results.csv
Files in process : 17-53-55 1144 2645_results.csv
Files in process : 17-54-35 1138 2424_results.csv
Files in process : 17-54-38 1135 2327_results.csv
Files in process : 17-57-25 1142 2582_results.csv
Files in process : 17-58-06 1144 2646_results.csv
Files in process : 17-58-09 1139 2466_results.csv
Files in process : 17-58-17 1145 2689_results.csv
Files in process : 17-58-23 1138 2425_results.csv
Files in process : 17-58-49 1135 2328_results.csv
Files in process : 18-01-47 1146 2703_results.csv
Files in process : 18-01-49 1142 2583_results.csv
Files in process : 18-02-10 1145 2690_results.csv
Files in process : 18-02-35 1139 2467_results.csv
Files in process : 18-03-08 1135 2329_results.csv
Files in process : 18-05-35 1138 2426_results.csv
Files in process : 18-06-13 1142 2584_results.csv
Files in process : 18-06-23 1145 2691_results.csv
Files in process : 18-06-53 1146 2704_results.csv
Files in process : 18-07-05 1135 2330_results.csv
Files in process : 18-07-07 1139 2468_results.csv
Files in process : 18-10-18 1145 2692_results.csv
Files in process : 18-11-11 1135 2331_results.csv
Files in process : 18-11-23 1139 2469_results.csv
Files in process : 18-11-26 1146 2705_results.csv
Files in process : 18-11-27 1142 2585_results.csv
Files in process : 18-13-11 1138 2427_results.csv
Files in process : 18-14-22 1145 2693_results.csv
Files in process : 18-15-14 1135 2332_results.csv
Files in process : 18-15-34 1146 2706_results.csv
Files in process : 18-15-48 1139 2470_results.csv
Files in process : 18-15-58 1142 2586_results.csv
Files in process : 18-16-46 1138 2428_results.csv
Files in process : 18-18-44 1145 2694_results.csv
Files in process : 18-19-28 1135 2333_results.csv
Files in process : 18-20-16 1142 2587_results.csv
Files in process : 18-20-21 1139 2471_results.csv
Files in process : 18-20-36 1144 2647_results.csv
Files in process : 18-20-42 1146 2707_results.csv
Files in process : 18-23-21 1145 2695_results.csv
Files in process : 18-23-27 1135 2334_results.csv
Files in process : 18-24-43 1142 2588_results.csv
Files in process : 18-24-47 1144 2648_results.csv
Files in process : 18-25-45 1146 2708_results.csv
Files in process : 18-27-15 1145 2696_results.csv
Files in process : 18-27-25 1135 2335_results.csv
Files in process : 18-29-00 1142 2589_results.csv
Files in process : 18-29-08 1144 2649_results.csv
Files in process : 18-30-05 1146 2709_results.csv
Files in process : 18-31-19 1145 2697_results.csv
Files in process : 18-31-25 1135 2336_results.csv
Files in process : 18-33-16 1144 2650_results.csv
Files in process : 18-33-24 1142 2590_results.csv
Files in process : 18-34-14 1146 2710_results.csv
Files in process : 18-35-08 1145 2698_results.csv
Files in process : 18-35-16 1135 2337_results.csv
Files in process : 18-37-22 1139 2472_results.csv
Files in process : 18-37-51 1142 2591_results.csv
Files in process : 18-38-26 1146 2711_results.csv
Files in process : 18-39-05 1145 2699_results.csv
Files in process : 18-41-23 1135 2338_results.csv
Files in process : 18-41-57 1139 2473_results.csv
Files in process : 18-42-19 1146 2712_results.csv
Files in process : 18-42-36 1142 2592_results.csv
Files in process : 18-42-49 1145 2700_results.csv
Files in process : 18-46-02 1135 2339_results.csv
Files in process : 18-46-17 1139 2474_results.csv
Files in process : 18-46-25 1146 2713_results.csv
Files in process : 18-46-59 1142 2593_results.csv
Files in process : 18-46-59 1145 2701_results.csv
Files in process : 18-50-19 1135 2340_results.csv
Files in process : 18-50-23 1146 2714_results.csv
Files in process : 18-50-41 1139 2475_results.csv
Files in process : 18-50-52 1145 2702_results.csv
Files in process : 18-51-25 1142 2594_results.csv
Files in process : 18-54-17 1135 2341_results.csv
Files in process : 18-55-07 1139 2476_results.csv
Files in process : 18-55-10 1146 2715_results.csv
Files in process : 18-56-00 1142 2595_results.csv
Files in process : 18-58-59 1146 2716_results.csv
Files in process : 18-59-08 1135 2342_results.csv
Files in process : 18-59-42 1139 2477_results.csv
Files in process : 19-01-36 1142 2596_results.csv
Files in process : 19-03-12 1146 2717_results.csv
Files in process : 19-03-21 1135 2343_results.csv
Files in process : 19-04-19 1139 2478_results.csv
Files in process : 19-04-51 1144 2651_results.csv
Files in process : 19-07-05 1146 2718_results.csv
Files in process : 19-07-35 1135 2344_results.csv
Files in process : 19-08-42 1139 2479_results.csv
Files in process : 19-08-55 1144 2652_results.csv
Files in process : 19-10-44 1146 2719_results.csv
Files in process : 19-12-10 1135 2345_results.csv
Files in process : 19-12-53 1144 2653_results.csv
Files in process : 19-13-40 1139 2480_results.csv
Files in process : 19-14-34 1146 2720_results.csv
Files in process : 19-16-58 1144 2654_results.csv
Files in process : 19-18-20 1146 2721_results.csv
Files in process : 19-18-21 1139 2481_results.csv
Files in process : 19-21-08 1144 2655_results.csv
Files in process : 19-22-05 1146 2722_results.csv
Files in process : 19-23-20 1135 2346_results.csv
Files in process : 19-23-29 1139 2482_results.csv
Files in process : 19-25-34 1144 2656_results.csv
Files in process : 19-25-35 1144 2657_results.csv
Files in process : 19-25-36 1144 2658_results.csv
Files in process : 19-25-36 1144 2659_results.csv
Files in process : 19-25-56 1146 2723_results.csv
Files in process : 19-27-17 1135 2347_results.csv
Files in process : 19-28-05 1139 2483_results.csv
Files in process : 19-30-35 1144 2660_results.csv
Files in process : 19-31-28 1135 2348_results.csv
Files in process : 19-33-21 1139 2484_results.csv
Files in process : 19-34-49 1144 2661_results.csv
Files in process : 19-35-13 1135 2349_results.csv
Files in process : 19-37-39 1139 2485_results.csv
Files in process : 19-39-04 1135 2350_results.csv
Files in process : 19-42-15 1139 2486_results.csv
Files in process : 19-42-54 1135 2351_results.csv
Files in process : 19-44-27 1144 2662_results.csv
Files in process : 19-46-56 1135 2352_results.csv
Files in process : 19-48-54 1144 2663_results.csv
Files in process : 19-50-26 1140 2487_results.csv
Files in process : 19-50-46 1135 2353_results.csv
Files in process : 19-53-17 1144 2664_results.csv
Files in process : 19-54-28 1135 2354_results.csv
Files in process : 19-54-59 1140 2488_results.csv
Files in process : 19-55-22 1146 2724_results.csv
Files in process : 19-57-33 1144 2665_results.csv
Files in process : 19-58-30 1135 2355_results.csv
Files in process : 19-59-13 1140 2489_results.csv
Files in process : 19-59-41 1146 2725_results.csv
Files in process : 20-01-48 1144 2666_results.csv
Files in process : 20-02-21 1135 2356_results.csv
Files in process : 20-03-40 1146 2726_results.csv
Files in process : 20-10-25 1146 2727_results.csv
Files in process : 20-10-45 1140 2490_results.csv
Files in process : 20-14-20 1146 2728_results.csv
Files in process : 20-18-47 1146 2729_results.csv
Files in process : 20-22-45 1146 2730_results.csv
Files in process : 20-26-09 1140 2491_results.csv
Files in process : 20-26-49 1146 2731_results.csv
Files in process : 20-30-48 1140 2492_results.csv
Files in process : 20-31-38 1146 2732_results.csv
Files in process : 20-35-38 1140 2493_results.csv
Files in process : 20-35-40 1146 2733_results.csv
Files in process : 20-39-53 1146 2734_results.csv
Files in process : 20-40-13 1140 2494_results.csv
Files in process : 20-42-45 1138 2429_results.csv
Files in process : 20-43-50 1146 2735_results.csv
Files in process : 20-44-48 1140 2495_results.csv
Files in process : 20-46-37 1138 2430_results.csv
Files in process : 20-48-04 1146 2736_results.csv
Files in process : 20-49-44 1140 2496_results.csv
Files in process : 20-50-04 1138 2431_results.csv

In [3]:
def clean_col_name(col):
    if col == "U238":
        return "U"
    elif col == "K39":
        return "K"
    elif col not in ['Filename']:
        # Remove trailing digits and letters after the element symbol
        # For example: "Al27" → "Al", "La139" → "La"
        return re.sub(r'[\dA-Z]+$', '', col)
    else:
        return col

In [4]:
def clean_filename(name):
    # Supprimer l'extension
    name = name.replace('_results.csv', '')
    # Enlever le timestamp ou les chiffres initiaux (facultatif selon ton besoin)
    name = re.sub(r'^\d{2}-\d{2}-\d{2} ?', '', name)  # retire "16-16-57 " ou "20-02-21 "
    # Séparer par "_" et ne garder que la première partie significative
    parts = name.split('_')
    return parts[0] if len(parts) == 1 else ' '.join(parts[:-1])

In [5]:
# Reading the CSV file with a MultiIndex header
# MultiIndex avec les 2 premières lignes
df = pd.read_csv("fusion_results.csv.gzip", compression='gzip', header=[0, 1])

# Delete columns that contain "counts" in the second level of the MultiIndex
df = df.loc[:, ~df.columns.get_level_values(1).str.contains("counts", case=False, na=False)]

# Keep only the first level of the MultiIndex
df.columns = df.columns.get_level_values(0)

# drop rows with time < 20 seconds
df = df[df['Time'] >= 20]

# drop the Time column
df.drop(columns=["Time"], inplace=True, errors='ignore')

# replace NaN by 0
df.fillna(0, inplace=True)

# Clean column names
df.columns = [clean_col_name(col) for col in df.columns]

# Add a new column before the filename column to sum all elements
df['Sum'] = df.drop(columns=['Filename']).sum(axis=1)
# Put the 'Sum' column just before the 'Filename' column
df = df[[col for col in df.columns if col != 'Filename'] + ['Filename']]

# Change the 'Filename' column to keep only the first part of the filename
df['Filename'] = df['Filename'].apply(clean_filename)

# separate the 'Filename' column into 'Core' and '# sample'
df[['Core', '# sample']] = df['Filename'].str.split(' ', n=1, expand=True)
# Put 0 for blank rows in '# sample'
df['# sample'] = df['# sample'].fillna('0')

# sort the DataFrame by 'Filename' but keep the blank rows first
df.sort_values(by='# sample', key=lambda x: x.str.strip(), inplace=True)
# Reorder the columns to have 'Blank' first

# Reset the index
df.reset_index(drop=True, inplace=True)

# Display the last few rows of the DataFrame
df.tail()

,Mg,Al,Si,K,Ca,Ti,Mn,Fe,Rb,Sr,Zr,Ba,Au,La,Ce,U,Sum,Filename,Core,# sample
1388140,0.0,3233.0414,0.000,0.0,0.0,239.32457,0.0,1345.8982,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,4818.26417,1146 2738,1146,2738
1388141,0.0,0.0000,0.000,0.0,0.0,0.00000,0.0,0.0000,0.0,0.0,0.0,0.0,4658.4232,0.0,0.0,0.0,4658.42320,1146 2738,1146,2738
1388142,0.0,0.0000,0.000,0.0,0.0,0.00000,0.0,0.0000,0.0,0.0,0.0,0.0,5993.9384,0.0,0.0,0.0,5993.93840,1146 2738,1146,2738
1388143,0.0,0.0000,0.000,0.0,0.0,0.00000,0.0,0.0000,0.0,0.0,0.0,0.0,10245.8300,0.0,0.0,0.0,10245.83000,1146 2738,1146,2738
1388144,0.0,0.0000,24065.507,0.0,0.0,0.00000,0.0,2397.0768,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,26462.58380,1146 2738,1146,2738

In [6]:
# drop the column U
df.drop(columns=['U'], inplace=True, errors='ignore')

In [7]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv("fusion_results_cleaned.csv.gzip", index=False, compression='gzip')

In [8]:
# import the Data AWI.xlsx as a DataFrame
awi_df = pd.read_excel("Add_data/Data AWI.xls", header=0)
awi_df.head()

   # sample     Depth  Conductivity  # Non-soluble dust  d18O  dD
0      2307  142.8627           NaN                 NaN   NaN NaN
1      2308  142.9132           NaN                 NaN   NaN NaN
2      2309  142.9637           NaN                 NaN   NaN NaN
3      2310  143.0142           NaN                 NaN   NaN NaN
4      2311  143.0647           NaN                 NaN   NaN NaN

In [9]:
# Clean columns
df.columns = df.columns.str.strip()
awi_df.columns = awi_df.columns.str.strip()

# Ensure merge column exists and is properly formatted
df['# sample'] = df['# sample'].astype(str).str.strip()
awi_df['# sample'] = awi_df['# sample'].astype(str).str.strip()

# Perform merge
merged_df = pd.merge(df, awi_df, on='# sample', how='left')

# Replace 0 values in the '# sample' column with 'Blank'
merged_df['# sample'] = merged_df['# sample'].replace('0', 'Blank')

# sort by depth
merged_df.sort_values(by='Depth', inplace=True)

# remove the row where Depth is > 125
merged_df = merged_df[merged_df['Depth'].astype(float) <= 125]

# remove the rows where Depth is < 105
merged_df = merged_df[merged_df['Depth'].astype(float) >= 105]

# Save and check
merged_df.to_csv("fusion_results_merged.csv.gzip", index=False, compression='gzip')
merged_df.head()

,Mg,Al,Si,K,Ca,Ti,Mn,Fe,Rb,Sr,...,Ce,Sum,Filename,Core,# sample,Depth,Conductivity,# Non-soluble dust,d18O,dD
470604,0.0,7866.8765,19696.529,0.0000,4241.7216,0.0,0.0,1932.7256,0.0,0.0,...,0.0,33737.85270,1139 2451,1139,2451,106.03535,0.103657,262.044776,-54.244194,-418.358575
470612,0.0,32396.3590,53410.377,4354.2529,5638.2739,0.0,0.0,3043.3326,0.0,0.0,...,0.0,99340.54338,1139 2451,1139,2451,106.03535,0.103657,262.044776,-54.244194,-418.358575
470606,0.0,0.0000,0.000,0.0000,0.0000,0.0,0.0,0.0000,0.0,0.0,...,0.0,12153.91300,1139 2451,1139,2451,106.03535,0.103657,262.044776,-54.244194,-418.358575
470607,0.0,0.0000,0.000,0.0000,0.0000,0.0,0.0,0.0000,0.0,0.0,...,0.0,4178.66360,1139 2451,1139,2451,106.03535,0.103657,262.044776,-54.244194,-418.358575
470608,0.0,0.0000,0.000,0.0000,0.0000,0.0,0.0,0.0000,0.0,0.0,...,0.0,14074.98200,1139 2451,1139,2451,106.03535,0.103657,262.044776,-54.244194,-418.358575

In [10]:
# display the number of unique # sample in the merged_df
merged_df['# sample'].nunique()

285

In [11]:
# display the number of particles in the merged_df
merged_df.shape[0]

919856